Avoiding duplicated code inside of the with index and `-NoIndex` tasks (#12169)
I am seeing [CI failures like this one](https://github.com/enso-org/enso/actions/runs/13010150839/job/36285908565?pr=12163#step:8:1085):
```
java.io.FileNotFoundException: built-distribution/enso-engine-2025.1.1-dev-linux-amd64/enso-2025.1.1-dev/lib/Standard/Base/2025.1.1-dev/package.yaml (No such file or directory)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at sbt.io.IO$.read(IO.scala:973)
at DistributionPackage$.fixLibraryManifest(DistributionPackage.scala:492)
at DistributionPackage$.$anonfun$copyLibraryCacheIncremental$2(DistributionPackage.scala:535)
at DistributionPackage$.$anonfun$copyLibraryCacheIncremental$2$adapted(DistributionPackage.scala:527)
at DistributionPackage$.$anonfun$copyLibraryCacheIncremental$1(DistributionPackage.scala:527)
at DistributionPackage$.$anonfun$copyLibraryCacheIncremental$1$adapted(DistributionPackage.scala:526)
at DistributionPackage$.copyLibraryCacheIncremental(DistributionPackage.scala:526)
at DistributionPackage$.createEnginePackage(DistributionPackage.scala:177)
```
I believe it was introduced recently when [bunch of tasks got duplicated](https://github.com/enso-org/enso/pull/12117/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R5145) in `build.sbt`. This change removes the duplication:
- `DistributionPackage.createEnginePackage` no longer build the indexes
- there is separete `DistributionPackage.indexStdLibs` function for that wrapped in `createStdLibsIndexes` task
- `buildEngineDistribution` just depends on all three sub tasks:
- `buildEngineDistributionNoIndex`
- `createEnginePackageNoIndex`
- `createStdLibsIndexes`

This shall avoid a situation when two different tasks are mangling with the same package/libraries structure.